model:
  ollama_url: "http://192.168.63.174:11434"
  embed_model: "nomic-embed-text" # bge-m3, nomic-embed-text, jinaai/jina-embeddings-v2-base-code
  embed_dim: 768
  llm_model: "qwen2.5:7b" # llama3.1:8b, mistral-small:24b

eval_model:
  ollama_url: "http://192.168.63.174:11434"
  llm_model: "qwen2.5:14b" # llama3.3:70b, llama3:70b-instruct, gpt-oss:120b

builder_model:
  ollama_url: "http://192.168.63.174:11434"
  llm_model: "qwen2.5:14b"

data:
  raw_file_path_DI: "/home/End_to_End_RAG/Data/CSR_20260122_v4_92_clean.jsonl"
  raw_file_path_GEN: "/home/End_to_End_RAG/Data/CSR_full.jsonl"
  qa_file_path_DI: "/home/End_to_End_RAG/Data/QA_43_clean.csv"
  qa_file_path_GEN: "/home/End_to_End_RAG/Data/qa_global_group_100.jsonl"

lightrag:
  lightrag_storage_path_DIR: "/home/End_to_End_RAG/lightrag_storage"
  lightrag_language: "Chinese"
  # lightrag_entity_types: [
  #     "Record",
  #     "Customer",
  #     "Engineer",
  #     "MaintenanceCategory",
  #     "Action",
  #     "Issue",
  #     "ActionCategory",
  #     "ActionSubcategory",
  #     "System",
  #     "Vulnerability",
  #     "Software",
  #     "Server"
  #   ]
  lightrag_entity_types: [
        "Record",
        "Engineer",
        "Customer",
        "Action",
        "Issue",
        "Department",
        "Server",
        "Version",
        "MaintainerAccount",
        "Service",
        "Report",
        "API",
        "Database",
        "System",
        "Log",
        "File",
        "GeoDB",
        "GitLab",
        "Cybereyes",
        "SSH Server",
        "Splunk",
        "Asset",
        "Identity",
        "Category",
        "Priority",
        "Container",
        "CSR",
        "FCB",
        "FWD03",
        "MG02",
        "Arcsight",
        "DNS_TUNNELING",
        "eStreamer",
        "KPMG",
        "IP_WhiteList",
        "VirusTotal",
        "AbuseIPDB",
        "TCode",
        "NTP",
        "Indexer",
        "Cluster",
        "KVstore",
        "PA",
        "FIsac",
        "DEP02",
        "MaintenanceRecord",
        "AuthorizationQuantity",
        "ServerPerformance",
        "SystemOptimizationSuggestion",
        "VersionUpdate",
        "EventType",
        "TrafficEvent",
        "ThreatEvent",
        "SystemEvent",
        "CPUUsageRate",
        "MemoryUsageRate",
        "DiskUsageRate",
        "HealthCheck",
        "UserRole",
        "OperatingSystem",
        "Vulnerability",
        "Certification",
        "ARP_table",
        "DC_ARP_table",
        "Crowdstrike",
        "Tenable_API_App",
        "Splunk_Add_on_for_Google_Cloud_Platform",
        "IP",
        "HostsFile",
        "LicenseMaster",
        "UF",
        "IIS_LOG",
        "DashboardStudio",
        "SaseUF",
        "SOAR",
        "MitreAttack",
        "ForcepointEndpointDLP",
        "CheckPointLogCLM",
        "DataModelDNSAMD",
        "ESAlert",
        "DC_ARP_report",
        "ARP_table_report",
        "Role",
        "BucketReplication",
        "Workaround",
        "Sourcetype",
        "AuthorizationQuantity",
        "LinuxHost",
        "CentOS",
        "KVstoreEngine",
        "SH",
        "FISAC",
        "API_IP_Application",
        "Trendmicro",
        "GCP",
        "Websense",
        "DLP",
        "BTDC2"
    ]

graph:
  backend: "neo4j"
  # extraction_mode: "hybrid" # transformer, schema, hybrid
  depth: 3
  use_entity_anchor: True
  storage_dir: "/home/End_to_End_RAG/graph_index"
  neo4j_database: "neo4j"
  neo4j_port: 7687